// Code generated by additional-properties DO NOT EDIT.

package acceptance

import (
	"encoding/json"
	"strings"
)

// MarshalJSON encodes the OmitEmpty struct to JSON with additional-properties
func (o OmitEmpty) MarshalJSON() ([]byte, error) {
	type Alias OmitEmpty
	aux := (Alias)(o)
	if aux.AP == nil {
		aux.AP = map[string]interface{}{}
	}
	aux.AP["fieldA"] = aux.FieldA
	return json.Marshal(aux.AP)
}

// UnmarshalJSON decodes JSON into the OmitEmpty struct with additional-properties
func (o *OmitEmpty) UnmarshalJSON(data []byte) error {
	type Alias OmitEmpty
	aux := (*Alias)(o)
	err := json.Unmarshal(data, &aux)
	if err != nil {
		return err
	}
	_ = json.Unmarshal(data, &o.AP)
	names := map[string]bool{
		"fieldA": true, "fielda": true,
	}
	for k := range o.AP {
		if names[k] {
			delete(o.AP, k)
			continue
		}
		if names[strings.ToLower(k)] {
			delete(o.AP, k)
		}
	}
	if len(o.AP) == 0 {
		o.AP = nil
	}
	return nil
}
